apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garmin
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/matthewtaylor1995/garmin
    newTag: latest