---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garmin-secrets
  namespace: garmin
spec:
  encryptedData:
    garmin_email: AgCbXFNVCzPWe1EgK4ZKawjkrHrYdQ/LfDYvEfXDj87ZuEuk3EudSyTwK0GAiOBHmZDcBg9hOjIEj0XXF1zGNYtKcc7rsuJCT+yqquUSsBNKq/V0UmkJITn2bVPlqvq7uzbjmgC4HC7PRRwQNjsWxZgNzXvqtIIrETuixA1rnvm8Asr4PypNJp6vO7wqSmOnqImb2sVigsoJiYJT0Lz3HH/C9eiGEtWYsy0eKBMvMFS+CKstzwRrK5Ci53rYvZSiuUOOMKM71dOzyumKtcJ1abQOX4DTW9WrgvOwg7NQtSQ/ardWWGtmzDA/sDw+l5PYjB7yuFVgVYLhmzd9rUNkTFSrJ/aReDeu4/4IwFj2U+lTsopbKJ8ZjQGx+Sh9ZPDRG5o4f5krJ/0OdSqFqozPRd/l5cUDtE7Pk9NIWKZnOJggL2jAIm+6RFKnp8LSmSOm9mkvfxcTs3m8FfkBefRytTf0PXudIjeczgLYkUMMvRYzJfc4M4O9l/zLUE/EFsXJAHIT4WvKHjlBdV3a9MCi11K9giQki8qObU6bCC0P+NyxjVTusgRt8kZMWb9KqKxR1zJzlAMsLdbgt08W0lm4LVSNjMDL6h1kRxTDDZTVDnDau45j/hHEEIwou38P2MvXEkkcBYM1EuXM2MyBz+jCa6bff2e9QplemW69d40jszVtEeLfxd6Kl9UvLMrX2RYJhwS/H6UoxYn/ZLM7cqQZMQz1pP4B68xKtYgpJgA=
    garmin_password: AgBBGId9W49DvzRSKaY/niyI6qYyb5PHzTeXMA93weXqaZqpsAuFjXYsPV4P4MTND21uc5DcX9z7hN6tFrUgsR0W3ewErOAu2+kE8ML4LrQjgSgikT1lROb9Qy5Lou5e5dRllhKSVg8LL/FPP2vBtJzFaribwdImHHzzhotLlkqtPvildOIPvhBATnqFGEhhr2tM6piQE7/wwEtro6vp9jFO8w7KSdOIwBHnvscgVT/z6Ib0biqNRDrY8vKhPGoP5vWen7r77YIhOufMtwxlw7j8ZnCQSxDUZudVNbPgWqO4G/S6P0X5lFy+9g9n8ovcFydR4gP4GlGh0Su6qMIhz9L6lnauRspW4WZTOErgNXptBisfG/vJrb7+TbVKvM3oBfiulKDV1fHJsMp6lj9HWMgozg00E00dNuHxPWN55DsVb7WqNWYN6XBbty9vn0BrvNQ4P/5MzUtjCdIgAHi3IRVcK+aEDdOk1JgXFyYqOCOoM91txlDJFZtlNVzrgUICwTiFJCoLzvjSFJQt9Guj/K2Vjh80hzl56lkw9TF2+BkwvRat2jCrEF2Oz/ZcU+L1HYn28aMKE3VjrywNBtcyWlNMWgmbzW7fHsuGGKSNPnAG4cxMTpnX1Cgwwd50xFLpozh8Vzst9Ke+4YG6cqUQDC5XOFOhVDK7JTfIgVbGFXn839e/GjQJxaY09jTxOEfBw2/tDWfVJ7gQEcmYlw==
  template:
    metadata:
      name: garmin-secrets
      namespace: garmin
