apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: charlton
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/matthewtaylor1995/cafcnews
    newTag: 8cac0fa4e11331bb3e851d6b815520ad64f7ee29