apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: charlton
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/matthewtaylor1995/cafcnews
    newTag: b8507ce8ec3d05b373845c1cdfa9d36906738707477f8fed0ff04e8f4ef65f8f