apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: charlton
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/matthewtaylor1995/cafcnews
    newTag: b5413f58dc92ef86b501c7c3c2c78f76f756c04ea84e2ce30a4e47847f686593