apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garmin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matthewtaylor1995/homelab.git
    targetRevision: main
    path: apps/garmin
  destination:
    server: https://kubernetes.default.svc
    namespace: garmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true